---
title: "Figure6"
author: "Jialu Wei"
date: "December 3, 2018"
output: html_document
---

---
```{r}
library(ggplot2)
library(ape)
library(dplyr)
library(seqinr)
library(tidyr)
```
# Selected samples for Figure6
```{r}
geno_final_ori <- read.csv("../../data/final_data.csv") %>% arrange(Sample)
passport <- read.csv("../../data/12864_2015_1444_MOESM1_ESM.csv")
samples <- c("BGV007859","LA1291","LA2254","BGV006931","BGV006753","BGV007208","BGV007208","BGV007155","BGV007137","BGV009320","LA2181_inra","BGV006639","PI_128216","LA2725","LA2974","LA1322","LA1330","GLP44") #manually input sample_id
snp <- colnames(geno_final_ori)
geno_selected <- subset(geno_final_ori,Sample %in% samples) #from full dataset, select samples with SNPs
geno_selected[] <- lapply(geno_selected, as.character)
recode <- geno_selected[,2:2960]  
```
 
# Recode SNPs to fasta.format
```{r}
code <- recode
code <- recode %>%
  replace(recode == "AA","A") %>%
  replace(recode == "AG","R") %>%
  replace(recode == "AT","W") %>%
  replace(recode == "AC","M") %>%
  replace(recode == "TT","T") %>%
  replace(recode == "TA","W") %>%
  replace(recode == "TC","Y") %>%
  replace(recode == "TG","K") %>%
  replace(recode == "CC","C") %>%
  replace(recode == "CA","M") %>%
  replace(recode == "CT","Y") %>%
  replace(recode == "CG","S") %>%
  replace(recode == "GG","G") %>%
  replace(recode == "GA","R") %>%
  replace(recode == "GT","K") 
code[is.na(code)] <- "?" 
unite_code <- unite(code, string,2:2959,sep = "") 
names <- code[,1]
final <- as.data.frame(t(code))
sequences <- final[2:2959,] %>% as.list.data.frame()
write.fasta(sequences = sequences,names = names, file.out = "figure6_samples.fasta")
```

# Install package `ggtree` for tree plotting
```{r}
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("DESeq2")
biocLite("ggtree")
library(ggtree)
```

# Import data from TATTSEL
`figure6_tree.nwk` is result file generated by `TASSEL` with running `Cladogram`.
```{r}
tree <- read.tree("figure6_tree.nwk")
ggtree(tree,branch.length = 'none') + geom_text(aes(label = node)) #inspect the figure with nodes labelled

```
# Flip branches
```{r}
tree_flipped <- ggtree(tree,branch.length = 'none') %>% flip(29,12) %>% flip(1,19) %>% flip(18,16) %>% flip(30,22)
tree_flipped # fliping branches to be same as theirs
```
# Visualizatin

```{r}
label <- c("SP_Peru2","SP_Peru8","SP_non_Andean","SP_Peru_4","SLC_Ecuador_1","SLC_Ecuador_3","SLC_Mesomeric","SLC_Peru2","SLC_Peru1","SP_Ecuador_3","SP_Ecuador_1","SP_Ecuador2","S.galapagense","S.neorickii","S.chmielewski","SP_Peru") #import tree information only contain sample name, to be same with their figure, I input the species name manually.

dt <- data.frame(label = tree$tip.label,species = label)

# using ggtree package for plotting
# geom_ti
tree_flipped %<+% dt + geom_tiplab(aes(label = paste0('bold(',species, ')~',label)),parse = T) +xlim(NA,18) + #add species name 
  geom_hilight(node = 24 ,fill = "mediumblue",alpha = .3,extend = 6.5) + geom_cladelabel(node=24, label="SLC", align=T, color='BLUE3',offset = 6.5, fontsize = 5, barsize = 1) + # highlight SLC group and put label aside
  geom_hilight(node = 28 ,fill = "green",alpha = .2,extend = 6.5) + geom_cladelabel(node=28, label="SP", align=T, color='GREEN',offset = 6.5, fontsize = 5, barsize = 1) + # highlight SP group and put label aside
  geom_hilight(node = 18 ,fill = "green",alpha = .2,extend = 6.5) + geom_cladelabel(node=18, label="SP", align=T, color='GREEN',offset = 6.5, fontsize = 5, barsize = 1) + 
  geom_hilight(node = 16,fill = "green",alpha = .2,extend = 6.5) + geom_cladelabel(node=16, label="SP", align=T, color='GREEN',offset = 6.5, fontsize = 5, barsize = 1)  

ggsave("Figure6.png")
ggsave("Figure6.pdf")

```

